name: Version Update

on:
  push:
    branches:
      - main
      - preview

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Update version in package.json
      run: node src/lib/version-utils.cjs 

    - name: Generate and update changelog
      run: node src/lib/update-changelog.cjs

    - name: Commit version change
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add package.json
        git commit -m "chore: update version for $GITHUB_REF version $VERSION"
        git push origin $GITHUB_REF

    - name: Create Git Tag
      run: |
        VERSION=$(node -p "require('./package.json').version")
        git tag -a "v$VERSION" -m "Release v$VERSION"
        git push origin --tags
