name: Version Update

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*' # You can also include other branches as needed

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Update version in package.json
        run: src/lib/version-utils.cjs # Adjust the path to your script

      - name: Commit version change
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json
          git commit -m "chore: update version for $GITHUB_REF"
          git push origin $GITHUB_REF

      # Optional: Create a Git tag for the new version
      - name: Create Git Tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin --tags
